### ISSUE TITLE
Add 'Tomorrow' with similar options as 'Yesterday'

### ISSUE THREAD

**Issue by DanielHouston** [tj/go-naturaldate#10]
## Prerequisites

* [x] I searched to see if the issue already exists.

## Description

I'd like to be able to specify relative dates in the near future as per the 'Yesterday' options

## Steps to Reproduce

N/A

**Comment by tj** [comment]
👍 SGTM, probably won't have time to get to it any time soon, but if anyone wants to PR

**Comment by DanielHouston** [comment]
I have no idea about peg, but gave it a shot: #11 
There are seemingly non-trivial changes to the generated file on my branch, including an issue where RuleIn was defined twice, which might be down to a later version of peg?

**Comment by tj** [comment]
awesome thanks! I forgot to add docs about peg, but I re-regenerated with my local copy anyway, thanks man!

**Comment by DanielHouston** [comment]
No worries, fits my use cases so I'm happy to help :tada: 
Can you please cut a release so I can keep my go.mod tidy?

**Comment by tj** [comment]
done!
